services:
  traefik:
    image: traefik:v3.6.4
    restart: unless-stopped
    command: [--configFile=/etc/traefik/traefik.yml]
    ports: ["80:80", "443:443"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./infra/traefik/dynamic:/etc/traefik/dynamic:ro
      - traefik_logs:/logs
      - traefik_certs:/certs:ro
    networks:
      observability: {}
      edge:
        aliases:
          - auth.hospital.lab
    depends_on:
      waf:
        condition: service_healthy
      cert-bootstrap:
        condition: service_completed_successfully
  cert-bootstrap:
    image: alpine:3.22
    restart: "no"
    entrypoint: [/bin/sh, /bootstrap/generate.sh]
    volumes:
      - ./infra/traefik/generate-cert.sh:/bootstrap/generate.sh:ro
      - ./infra/traefik/dynamic:/dynamic
      - traefik_certs:/certs
    networks: [edge]
  waf:
    image: owasp/modsecurity-crs:apache
    restart: unless-stopped
    environment:
      BACKEND: http://waf-backend:80
      PARANOIA: "1"
      ANOMALY_INBOUND: "5"
      REMOTEIP_HEADER: X-Real-IP
      REMOTEIP_INT_PROXY: 172.16.0.0/12
      MODSEC_RULE_ENGINE: "On"
      MODSEC_AUDIT_ENGINE: RelevantOnly
      MODSEC_AUDIT_LOG: /var/log/waf/audit.json
      MODSEC_AUDIT_LOG_FORMAT: JSON
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_AUDIT_LOG_PARTS: AHZ
    volumes:
      - ./infra/waf/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
      - ./infra/waf/blocklists:/etc/modsecurity-blocklists:ro
      - waf_logs:/var/log/waf
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    networks: [edge]
    depends_on:
      waf-backend:
        condition: service_healthy
      waf-log-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "httpd -t"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 20s
  waf-backend:
    image: nginxdemos/hello:plain-text
    restart: unless-stopped
    networks: [edge]
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 5s
      timeout: 3s
      retries: 6
  waf-log-init:
    image: owasp/modsecurity-crs:apache
    restart: "no"
    user: "0:0"
    entrypoint: [/bin/sh, -c]
    command:
      - "mkdir -p /var/log/waf && touch /var/log/waf/audit.json && chown httpd:httpd /var/log/waf /var/log/waf/audit.json && chmod 0755 /var/log/waf && chmod 0644 /var/log/waf/audit.json"
    volumes:
      - waf_logs:/var/log/waf
volumes:
  waf_logs: {}
